mode: 'emotion'
display_size: 2
emotion:
    a: neu
    b: ang
Discriminator:
    act: 'relu'
    dropout_rate: 0
    sn: True
SpeakerEncoder:
    c_in: 512
    c_h: 256
    c_out: 256
    kernel_size: 5
    bank_size: 8
    bank_scale: 1
    c_bank: 128
    n_conv_blocks: 6
    n_dense_blocks: 6
    subsample: [1, 2, 1, 2, 1, 2]
    act: 'relu'
    dropout_rate: 0
ContentEncoder:
    c_in: 512
    c_h: 128
    c_out: 128
    kernel_size: 5
    bank_size: 8
    bank_scale: 1
    c_bank: 128
    n_conv_blocks: 6
    subsample: [1, 2, 1, 2, 1, 2]
    act: 'relu'
    dropout_rate: 0
Decoder:
    c_in: 128
    c_cond: 256
    c_h: 128
    c_out: 512
    kernel_size: 5
    n_conv_blocks: 6
    upsample: [2, 1, 2, 1, 2, 1]
    act: 'relu'
    sn: False
    dropout_rate: 0
data_loader:
    segment_size: 128
    frame_size: 1
    batch_size: 64
    shuffle: True
    load_mel: True
    num_workers: 30
optimizer:
    lr: 0.0001
    beta1: 0.9
    beta2: 0.999
    amsgrad: True
    weight_decay: 0.0001
    grad_norm: 5
    gamma: 1
    step_size: 100000 
lambda:
    gan_w: 1
    recon_x_w: 500
    recon_s_w: 1
    recon_c_w: 1
    gp_w: 10
sample_rate: 16000
